services:
  recollect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3795:5173 #svelte app
      - 8090:8090 #pocketbase
    volumes: 
      - ${PB_DATA_PATH}:/app/db/pb_data
    restart: on-failure:5

# docker compose -p recollect -f docker-compose.yml up --build -d