version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3795:3795"
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/db/pb_data
    command: ["serve", "--dir", "/pb_data"]

volumes:
  pb_data: